import type { Restaurante } from "../types"

export const brasaBurger: Restaurante = {
  slug: "brasa-burger",
  nome: "Brasa Burger & Co.",
  tipo: "Hamburgueria artesanal",
  cidade: "Campo Grande · MS",
  endereco: "Rua das Brasas, 120 — Centro",
  horario: "Ter a Dom · 18h às 00h",
  instagram: "@brasaburger.demo",
  branding: {
    primary: "#FF6A1A",
    onPrimary: "#160B06",
    accent: "#FFC93C",
    bg: "#0F0805",
    surface: "#1E120B",
    text: "#FFF4EA",
    muted: "#B9A08E",
    fontDisplay: "anton",
    fontBody: "jakarta",
    radius: 14,
    logoText: "BRASA",
    logoMark: "🔥",
    tagline: "Smash na chapa, fogo de verdade.",
  },
  categorias: [
    { id: "burgers", nome: "Burgers", emoji: "🍔" },
    { id: "porcoes", nome: "Porções", emoji: "🍟" },
    { id: "bebidas", nome: "Bebidas", emoji: "🥤" },
    { id: "sobremesas", nome: "Sobremesas", emoji: "🍫" },
  ],
  itens: [
    {
      id: "bacon-duplo",
      nome: "Bacon Duplo",
      descricao: "Dois smash de 90g, cheddar inglês derretido, bacon crocante, alface, tomate e maionese da casa no pão brioche.",
      preco: 42.9,
      categoria: "burgers",
      midia: "bacon-duplo",
      pedidos30d: 1284,
      pedidosMesAnterior: 1010,
      curtidas: 3920,
      tempoPreparo: "15 min",
      serve: "1 pessoa",
      combinaCom: "chopp-pilsen",
      destaqueDoMes: true,
      notaDoChef: "O queridinho da casa: a crosta do smash com o bacon defumado é o que faz a fila dobrar a esquina.",
    },
    {
      id: "smash-classico",
      nome: "Smash Clássico",
      descricao: "Smash de 120g selado na chapa, cheddar, alface, tomate e molho especial. Simples e perfeito.",
      preco: 32.9,
      categoria: "burgers",
      midia: "smash-classico",
      pedidos30d: 1102,
      pedidosMesAnterior: 1150,
      curtidas: 2810,
      tempoPreparo: "12 min",
      serve: "1 pessoa",
      combinaCom: "batata-rustica",
    },
    {
      id: "batata-rustica",
      nome: "Batata Rústica",
      descricao: "Batatas cortadas na casa, fritas duas vezes, com flor de sal e ketchup artesanal.",
      preco: 24.9,
      categoria: "porcoes",
      midia: "batata-rustica",
      pedidos30d: 980,
      pedidosMesAnterior: 870,
      curtidas: 1640,
      tempoPreparo: "10 min",
      serve: "2 pessoas",
      tags: ["vegetariano", "compartilhar"],
    },
    {
      id: "milkshake-morango",
      nome: "Shake de Morango",
      descricao: "Sorvete de baunilha batido com morango fresco, chantilly, granulado e cereja no topo.",
      preco: 22.9,
      categoria: "bebidas",
      midia: "milkshake-morango",
      pedidos30d: 512,
      pedidosMesAnterior: 300,
      curtidas: 2240,
      tags: ["vegetariano", "novo"],
      destaqueDoMes: true,
      notaDoChef: "Lançamento de outubro: morango da estação e calda feita aqui todo dia.",
    },
    {
      id: "milkshake-ovomaltine",
      nome: "Shake Ovomaltine",
      descricao: "Clássico crocante com calda de chocolate belga e chantilly.",
      preco: 23.9,
      categoria: "bebidas",
      midia: "milkshake-ovomaltine",
      pedidos30d: 640,
      pedidosMesAnterior: 690,
      curtidas: 1980,
      tags: ["vegetariano"],
    },
    {
      id: "chopp-pilsen",
      nome: "Chopp Pilsen 500ml",
      descricao: "Chopp gelado tirado na hora, colarinho cremoso. Leve e refrescante.",
      preco: 18.9,
      precoAntigo: 22.9,
      categoria: "bebidas",
      midia: "chopp-pilsen",
      pedidos30d: 1190,
      pedidosMesAnterior: 1050,
      curtidas: 1320,
      tags: ["alcoolico"],
    },
    {
      id: "limonada-suica",
      nome: "Limonada Suíça",
      descricao: "Limão tahiti batido com leite condensado, gelo e hortelã.",
      preco: 14.9,
      categoria: "bebidas",
      midia: "limonada-suica",
      pedidos30d: 430,
      pedidosMesAnterior: 410,
      curtidas: 760,
      tags: ["vegetariano"],
    },
    {
      id: "brownie-sorvete",
      nome: "Brownie com Sorvete",
      descricao: "Brownie quentinho de chocolate 70%, sorvete de baunilha e calda que escorre na mesa.",
      preco: 26.9,
      categoria: "sobremesas",
      midia: "brownie-sorvete",
      pedidos30d: 365,
      pedidosMesAnterior: 290,
      curtidas: 2050,
      tags: ["vegetariano"],
      combinaCom: "milkshake-ovomaltine",
    },
  ],
}
