import type { Restaurante } from "../types"

export const cantinaNonna: Restaurante = {
  slug: "cantina-nonna",
  nome: "Cantina Nonna",
  tipo: "Cantina italiana",
  cidade: "Curitiba · PR",
  endereco: "Rua Santa Felicidade, 1890",
  horario: "Qua a Dom · 11h30 às 23h",
  instagram: "@cantinanonna.demo",
  branding: {
    primary: "#1F6B3A",
    onPrimary: "#FFF8EC",
    accent: "#C8302B",
    bg: "#FBF4E8",
    surface: "#FFFFFF",
    text: "#2A1E14",
    muted: "#7A6A58",
    fontDisplay: "fraunces",
    fontBody: "jakarta",
    radius: 22,
    logoText: "Cantina Nonna",
    logoMark: "N",
    logo: "/midia/cantina-nonna/logo.svg",
    tagline: "Receita de família desde 1962.",
  },
  categorias: [
    { id: "pizzas", nome: "Pizzas", emoji: "🍕" },
    { id: "massas", nome: "Massas", emoji: "🍝" },
    { id: "vinhos", nome: "Vinhos & Drinks", emoji: "🍷" },
    { id: "dolci", nome: "Dolci", emoji: "🍰" },
  ],
  itens: [
    {
      id: "pizza-margherita",
      nome: "Margherita da Nonna",
      descricao: "Molho de tomate San Marzano, muçarela de búfala, manjericão fresco e azeite extravirgem.",
      preco: 74,
      categoria: "pizzas",
      midia: "pizza-margherita",
      pedidos30d: 1040,
      pedidosMesAnterior: 980,
      curtidas: 3880,
      tempoPreparo: "20 min",
      serve: "2 a 3 pessoas",
      tags: ["vegetariano", "compartilhar"],
      combinaCom: "vinho-tinto",
    },
    {
      id: "pizza-calabresa",
      nome: "Calabresa Artesanal",
      descricao: "Calabresa defumada da casa, cebola roxa, azeitonas pretas e orégano.",
      preco: 69,
      categoria: "pizzas",
      midia: "pizza-calabresa",
      pedidos30d: 1220,
      pedidosMesAnterior: 1190,
      curtidas: 2900,
      tempoPreparo: "20 min",
      serve: "2 a 3 pessoas",
      tags: ["compartilhar", "picante"],
      combinaCom: "spritz",
    },
    {
      id: "spaghetti-sugo",
      nome: "Spaghetti al Sugo",
      descricao: "Massa fresca feita na casa, sugo de tomate cozido lentamente, manjericão e parmesão.",
      preco: 58,
      categoria: "massas",
      midia: "spaghetti-sugo",
      pedidos30d: 740,
      pedidosMesAnterior: 520,
      curtidas: 2410,
      tempoPreparo: "16 min",
      tags: ["vegetariano"],
      destaqueDoMes: true,
      notaDoChef: "A receita original da Nonna Lina. Em outubro, parmesão 24 meses ralado na mesa.",
      combinaCom: "vinho-tinto",
    },
    {
      id: "vinho-tinto",
      nome: "Taça de Montepulciano",
      descricao: "Tinto italiano de corpo médio, notas de cereja e especiarias.",
      preco: 36,
      categoria: "vinhos",
      midia: "vinho-tinto",
      pedidos30d: 680,
      pedidosMesAnterior: 640,
      curtidas: 980,
      tags: ["alcoolico"],
    },
    {
      id: "spritz",
      nome: "Aperitivo Spritz",
      descricao: "Bitter de laranja, espumante, água com gás e uma rodela de laranja.",
      preco: 34,
      precoAntigo: 39,
      categoria: "vinhos",
      midia: "spritz",
      pedidos30d: 590,
      pedidosMesAnterior: 410,
      curtidas: 1650,
      tags: ["alcoolico"],
    },
    {
      id: "caipirinha",
      nome: "Caipirinha de Limão",
      descricao: "Cachaça artesanal, limão tahiti e gelo picado. A brasileira da cantina.",
      preco: 26,
      categoria: "vinhos",
      midia: "caipirinha",
      pedidos30d: 450,
      pedidosMesAnterior: 470,
      curtidas: 720,
      tags: ["alcoolico"],
    },
    {
      id: "tiramisu-nonna",
      nome: "Tiramisù",
      descricao: "Biscoito champagne no café, creme de mascarpone e cacau polvilhado na hora.",
      preco: 29,
      categoria: "dolci",
      midia: "tiramisu-nonna",
      pedidos30d: 510,
      pedidosMesAnterior: 430,
      curtidas: 2630,
      tags: ["vegetariano"],
      destaqueDoMes: true,
      notaDoChef: "Montado de manhã, servido gelado. Não chega até as 22h.",
    },
  ],
}
