import type { Restaurante } from "../types"

export const kazeSushi: Restaurante = {
  slug: "kaze-sushi",
  nome: "Kaze Sushi Bar",
  tipo: "Japonês contemporâneo",
  cidade: "São Paulo · SP",
  endereco: "Al. dos Ventos, 88 — Pinheiros",
  horario: "Seg a Sáb · 12h às 15h · 19h às 23h",
  instagram: "@kaze.demo",
  branding: {
    primary: "#E8443A",
    onPrimary: "#FFFFFF",
    accent: "#F4E9D8",
    bg: "#0B0A0E",
    surface: "#16141B",
    text: "#F7F2EA",
    muted: "#9C97A6",
    fontDisplay: "shippori",
    fontBody: "jakarta",
    radius: 4,
    logoText: "風 KAZE",
    logoMark: "風",
    tagline: "O vento traz o peixe fresco do dia.",
  },
  categorias: [
    { id: "pecas", nome: "Peças", emoji: "🍣" },
    { id: "quentes", nome: "Quentes", emoji: "🍜" },
    { id: "drinks", nome: "Drinks", emoji: "🍸" },
    { id: "doces", nome: "Doces", emoji: "🍵" },
  ],
  itens: [
    {
      id: "combinado-kaze",
      nome: "Combinado Kaze — 20 peças",
      descricao: "Nigiris de salmão, atum e peixe branco, uramaki e hossomaki do dia. Seleção do sushiman.",
      preco: 119,
      categoria: "pecas",
      midia: "combinado-kaze",
      pedidos30d: 860,
      pedidosMesAnterior: 790,
      curtidas: 4120,
      serve: "2 pessoas",
      tags: ["compartilhar"],
      combinaCom: "gin-yuzu",
    },
    {
      id: "ramen-tonkotsu",
      nome: "Ramen Tonkotsu",
      descricao: "Caldo de porco cozido por 14h, lámen artesanal, chashu, ovo marinado, nori e cebolinha.",
      preco: 58,
      categoria: "quentes",
      midia: "ramen-tonkotsu",
      pedidos30d: 920,
      pedidosMesAnterior: 640,
      curtidas: 3560,
      tempoPreparo: "18 min",
      destaqueDoMes: true,
      notaDoChef: "Outubro esfriou: o tonkotsu ganhou ovo extra sem custo durante o mês todo.",
      combinaCom: "soda-lichia",
    },
    {
      id: "gin-yuzu",
      nome: "Gin Tônica de Yuzu",
      descricao: "Gin japonês, tônica artesanal, yuzu e alecrim tostado.",
      preco: 39,
      categoria: "drinks",
      midia: "gin-yuzu",
      pedidos30d: 610,
      pedidosMesAnterior: 600,
      curtidas: 1480,
      tags: ["alcoolico"],
    },
    {
      id: "soda-lichia",
      nome: "Soda de Lichia",
      descricao: "Xarope de lichia da casa, água com gás e limão siciliano.",
      preco: 19,
      categoria: "drinks",
      midia: "soda-lichia",
      pedidos30d: 380,
      pedidosMesAnterior: 210,
      curtidas: 940,
      tags: ["vegetariano", "novo"],
    },
    {
      id: "petit-matcha",
      nome: "Petit Gâteau & Matcha",
      descricao: "Petit gâteau de chocolate amargo com sorvete de matcha cerimonial.",
      preco: 32,
      categoria: "doces",
      midia: "petit-matcha",
      pedidos30d: 290,
      pedidosMesAnterior: 260,
      curtidas: 1720,
      tags: ["vegetariano"],
      destaqueDoMes: true,
      notaDoChef: "A sobremesa que mais rende foto no salão.",
    },
  ],
}
