import type { Restaurante } from "../types"

// Demonstração para apresentar ao Road House Old Sheep (Campo Grande/MS).
// Itens e preços do cardápio deles; fotos tiradas do cardápio e do Instagram
// (vídeos gerados com scripts/cardapio/fotos_para_videos.py).
// Os números de pedidos e curtidas são ilustrativos, só para a demo.
export const roadHouse: Restaurante = {
  slug: "road-house",
  nome: "Road House Old Sheep",
  tipo: "Burger · Bar · Almoço",
  cidade: "Campo Grande · MS",
  endereco: "R. Jacarepaguá, 8",
  horario: "Ter a Sex · 17h às 23h · Sáb · 8h30 às 23h",
  instagram: "@roadhouse_oldsheep",
  branding: {
    primary: "#C8373D",
    onPrimary: "#FFF6E8",
    accent: "#F2C14E",
    bg: "#10151F",
    surface: "#1B2232",
    text: "#F7EEDC",
    muted: "#A9A49A",
    fontDisplay: "anton",
    fontBody: "jakarta",
    radius: 14,
    logoText: "ROAD HOUSE",
    logoMark: "RH",
    logo: "/midia/road-house/logo.png",
    tagline: "Burger, bar e kustom kulture.",
  },
  categorias: [
    { id: "burgers", nome: "Hambúrguer", emoji: "🍔" },
    { id: "porcoes", nome: "Baldinhos e porções", emoji: "🍗" },
    { id: "bebidas", nome: "Bebidas", emoji: "🥤" },
  ],
  itens: [
    {
      id: "smash-house",
      nome: "Smash House",
      descricao: "2 smash de 80g, cebola roxa, american cheese, picles, tomate, alface e molho Big House.",
      preco: 46,
      categoria: "burgers",
      midia: "smash-house",
      pedidos30d: 860,
      pedidosMesAnterior: 720,
      curtidas: 2140,
      tempoPreparo: "15 min",
      serve: "1 pessoa",
      combinaCom: "fritas-cheddar-bacon",
      destaqueDoMes: true,
      notaDoChef: "O burger que leva o nome da casa: dois smash bem selados e o molho Big House, receita nossa.",
    },
    {
      id: "cheddar-burguer",
      nome: "Cheddar Burguer",
      descricao: "Pão brioche, 2 smash de 90g, cheddar cremoso e bacon crocante.",
      preco: 45,
      categoria: "burgers",
      midia: "cheddar-burguer",
      pedidos30d: 790,
      pedidosMesAnterior: 810,
      curtidas: 1980,
      tempoPreparo: "15 min",
      serve: "1 pessoa",
      combinaCom: "batatas-fritas",
    },
    {
      id: "onion-smash",
      nome: "Onion Smash",
      descricao: "2 smash de 80g chapeados com cebola, american cheese e farofa de bacon.",
      preco: 46,
      categoria: "burgers",
      midia: "onion-smash",
      pedidos30d: 640,
      pedidosMesAnterior: 520,
      curtidas: 1510,
      tempoPreparo: "15 min",
      serve: "1 pessoa",
      tags: ["novo"],
    },
    {
      id: "road-burger",
      nome: "Road Burger",
      descricao: "Burger artesanal de 160g grelhado no ponto, pão brioche leve, molho da casa e queijo no capricho.",
      preco: 34,
      categoria: "burgers",
      midia: "road-burger",
      pedidos30d: 580,
      pedidosMesAnterior: 600,
      curtidas: 1270,
      tempoPreparo: "15 min",
      serve: "1 pessoa",
      combinaCom: "batatas-fritas",
    },
    {
      id: "kids-burger",
      nome: "Kids Burger",
      descricao: "Clássico pão, carne e queijo, acompanhado de batatas fritas.",
      preco: 42,
      categoria: "burgers",
      midia: "kids-burger",
      pedidos30d: 210,
      pedidosMesAnterior: 190,
      curtidas: 430,
      serve: "1 criança",
    },
    {
      id: "espetinho-completo",
      nome: "Espetinho Completo",
      descricao: "Espeto de 150g na brasa, suculento e no ponto. Acompanha farofa crocante da casa, vinagrete e mandioca.",
      preco: 35,
      categoria: "porcoes",
      midia: "espetinho-completo",
      pedidos30d: 520,
      pedidosMesAnterior: 480,
      curtidas: 990,
      tempoPreparo: "20 min",
      serve: "1 pessoa",
      tags: ["almoço"],
    },
    {
      id: "tulipinhas-crocantes",
      nome: "Tulipinhas Crocantes",
      descricao: "8 meio-asas empanadas com a crocância perfeita. Fritas na hora, com tempero exclusivo da casa.",
      preco: 48,
      categoria: "porcoes",
      midia: "tulipinhas-crocantes",
      pedidos30d: 470,
      pedidosMesAnterior: 400,
      curtidas: 1120,
      serve: "2 pessoas",
      tags: ["compartilhar"],
    },
    {
      id: "coxinha-pulled-pork",
      nome: "Coxinha de Pulled Pork",
      descricao: "Porção com 7 unidades. Massa de mandioca e mandioquinha com pulled pork desfiado, recheada com muçarela.",
      preco: 45,
      categoria: "porcoes",
      midia: "coxinha-pulled-pork",
      pedidos30d: 430,
      pedidosMesAnterior: 300,
      curtidas: 1340,
      serve: "2 pessoas",
      tags: ["compartilhar"],
      destaqueDoMes: true,
      notaDoChef: "Pulled pork defumado aqui mesmo, envolvido numa massa de mandioca. Não dá pra comer uma só.",
    },
    {
      id: "bolinho-de-brisket",
      nome: "Bolinho de Brisket",
      descricao: "Bolinhos crocantes recheados com brisket defumado. Rústicos, potentes e cheios de personalidade.",
      preco: 45,
      categoria: "porcoes",
      midia: "bolinho-de-brisket",
      pedidos30d: 390,
      pedidosMesAnterior: 350,
      curtidas: 870,
      serve: "2 pessoas",
      tags: ["compartilhar"],
    },
    {
      id: "iscas-de-frango",
      nome: "Iscas de Frango Empanadas",
      descricao: "Iscas de frango empanadas, suculentas por dentro e sequinhas por fora. Servidas no baldinho Road House.",
      preco: 45,
      categoria: "porcoes",
      midia: "iscas-de-frango",
      pedidos30d: 360,
      pedidosMesAnterior: 380,
      curtidas: 640,
      serve: "2 pessoas",
      tags: ["compartilhar"],
    },
    {
      id: "palitos-queijo-coalho",
      nome: "Palitos de Queijo Coalho",
      descricao: "Porção com 5 palitos de queijo coalho empanados, douradinhos por fora e derretendo por dentro.",
      preco: 40,
      categoria: "porcoes",
      midia: "palitos-queijo-coalho",
      pedidos30d: 330,
      pedidosMesAnterior: 290,
      curtidas: 710,
      serve: "2 pessoas",
      tags: ["vegetariano", "compartilhar"],
    },
    {
      id: "fritas-cheddar-bacon",
      nome: "Fritas com Cheddar e Bacon",
      descricao: "Batatas sequinhas cobertas com cheddar cremoso e farofa de bacon.",
      preco: 35,
      categoria: "porcoes",
      midia: "fritas-cheddar-bacon",
      pedidos30d: 610,
      pedidosMesAnterior: 560,
      curtidas: 1180,
      serve: "2 pessoas",
      tags: ["compartilhar"],
    },
    {
      id: "batatas-fritas",
      nome: "Batatas Fritas",
      descricao: "Batatas sequinhas e levemente salgadas, perfeitas para qualquer ocasião.",
      preco: 25,
      categoria: "porcoes",
      midia: "batatas-fritas",
      pedidos30d: 540,
      pedidosMesAnterior: 530,
      curtidas: 620,
      serve: "2 pessoas",
      tags: ["vegetariano"],
    },
    {
      id: "coca-cola",
      nome: "Coca-Cola Lata 350ml",
      descricao: "Gelada, do jeito certo.",
      preco: 8,
      categoria: "bebidas",
      midia: "coca-cola",
      pedidos30d: 700,
      pedidosMesAnterior: 680,
      curtidas: 150,
    },
    {
      id: "coca-zero",
      nome: "Coca-Cola Zero Lata 350ml",
      descricao: "Zero açúcar, mesmo sabor.",
      preco: 8,
      categoria: "bebidas",
      midia: "coca-zero",
      pedidos30d: 320,
      pedidosMesAnterior: 300,
      curtidas: 90,
    },
  ],
}
