import type { Restaurante } from "./types"

// Restaurantes fictícios usados na demonstração.
// Em produção estes dados viriam do banco (ex.: Supabase) e do painel do restaurante.

export const RESTAURANTES: Restaurante[] = [
  {
    slug: "brasa-burger",
    nome: "Brasa Burger & Co.",
    tipo: "Hamburgueria artesanal",
    cidade: "Campo Grande · MS",
    endereco: "Rua das Brasas, 120 — Centro",
    horario: "Ter a Dom · 18h às 00h",
    instagram: "@brasaburger.demo",
    mesas: 24,
    branding: {
      primary: "#FF6A1A",
      onPrimary: "#160B06",
      accent: "#FFC93C",
      bg: "#0F0805",
      surface: "#1E120B",
      text: "#FFF4EA",
      muted: "#B9A08E",
      fontDisplay: "anton",
      fontBody: "jakarta",
      radius: 14,
      logoText: "BRASA",
      logoMark: "🔥",
      tagline: "Smash na chapa, fogo de verdade.",
    },
    categorias: [
      { id: "burgers", nome: "Burgers", emoji: "🍔" },
      { id: "porcoes", nome: "Porções", emoji: "🍟" },
      { id: "bebidas", nome: "Bebidas", emoji: "🥤" },
      { id: "sobremesas", nome: "Sobremesas", emoji: "🍫" },
    ],
    itens: [
      {
        id: "bacon-duplo",
        nome: "Bacon Duplo",
        descricao: "Dois smash de 90g, cheddar inglês derretido, bacon crocante, alface, tomate e maionese da casa no pão brioche.",
        preco: 42.9,
        categoria: "burgers",
        midia: "bacon-duplo",
        pedidos30d: 1284,
        pedidosMesAnterior: 1010,
        curtidas: 3920,
        tempoPreparo: "15 min",
        serve: "1 pessoa",
        combinaCom: "chopp-pilsen",
        destaqueDoMes: true,
        notaDoChef: "O queridinho da casa: a crosta do smash com o bacon defumado é o que faz a fila dobrar a esquina.",
      },
      {
        id: "smash-classico",
        nome: "Smash Clássico",
        descricao: "Smash de 120g selado na chapa, cheddar, alface, tomate e molho especial. Simples e perfeito.",
        preco: 32.9,
        categoria: "burgers",
        midia: "smash-classico",
        pedidos30d: 1102,
        pedidosMesAnterior: 1150,
        curtidas: 2810,
        tempoPreparo: "12 min",
        serve: "1 pessoa",
        combinaCom: "batata-rustica",
      },
      {
        id: "batata-rustica",
        nome: "Batata Rústica",
        descricao: "Batatas cortadas na casa, fritas duas vezes, com flor de sal e ketchup artesanal.",
        preco: 24.9,
        categoria: "porcoes",
        midia: "batata-rustica",
        pedidos30d: 980,
        pedidosMesAnterior: 870,
        curtidas: 1640,
        tempoPreparo: "10 min",
        serve: "2 pessoas",
        tags: ["vegetariano", "compartilhar"],
      },
      {
        id: "milkshake-morango",
        nome: "Shake de Morango",
        descricao: "Sorvete de baunilha batido com morango fresco, chantilly, granulado e cereja no topo.",
        preco: 22.9,
        categoria: "bebidas",
        midia: "milkshake-morango",
        pedidos30d: 512,
        pedidosMesAnterior: 300,
        curtidas: 2240,
        tags: ["vegetariano", "novo"],
        destaqueDoMes: true,
        notaDoChef: "Lançamento de outubro: morango da estação e calda feita aqui todo dia.",
      },
      {
        id: "milkshake-ovomaltine",
        nome: "Shake Ovomaltine",
        descricao: "Clássico crocante com calda de chocolate belga e chantilly.",
        preco: 23.9,
        categoria: "bebidas",
        midia: "milkshake-ovomaltine",
        pedidos30d: 640,
        pedidosMesAnterior: 690,
        curtidas: 1980,
        tags: ["vegetariano"],
      },
      {
        id: "chopp-pilsen",
        nome: "Chopp Pilsen 500ml",
        descricao: "Chopp gelado tirado na hora, colarinho cremoso. Leve e refrescante.",
        preco: 18.9,
        precoAntigo: 22.9,
        categoria: "bebidas",
        midia: "chopp-pilsen",
        pedidos30d: 1190,
        pedidosMesAnterior: 1050,
        curtidas: 1320,
        tags: ["alcoolico"],
      },
      {
        id: "limonada-suica",
        nome: "Limonada Suíça",
        descricao: "Limão tahiti batido com leite condensado, gelo e hortelã.",
        preco: 14.9,
        categoria: "bebidas",
        midia: "limonada-suica",
        pedidos30d: 430,
        pedidosMesAnterior: 410,
        curtidas: 760,
        tags: ["vegetariano"],
      },
      {
        id: "brownie-sorvete",
        nome: "Brownie com Sorvete",
        descricao: "Brownie quentinho de chocolate 70%, sorvete de baunilha e calda que escorre na mesa.",
        preco: 26.9,
        categoria: "sobremesas",
        midia: "brownie-sorvete",
        pedidos30d: 365,
        pedidosMesAnterior: 290,
        curtidas: 2050,
        tags: ["vegetariano"],
        combinaCom: "milkshake-ovomaltine",
      },
    ],
  },
  {
    slug: "kaze-sushi",
    nome: "Kaze Sushi Bar",
    tipo: "Japonês contemporâneo",
    cidade: "São Paulo · SP",
    endereco: "Al. dos Ventos, 88 — Pinheiros",
    horario: "Seg a Sáb · 12h às 15h · 19h às 23h",
    instagram: "@kaze.demo",
    mesas: 16,
    branding: {
      primary: "#E8443A",
      onPrimary: "#FFFFFF",
      accent: "#F4E9D8",
      bg: "#0B0A0E",
      surface: "#16141B",
      text: "#F7F2EA",
      muted: "#9C97A6",
      fontDisplay: "shippori",
      fontBody: "jakarta",
      radius: 4,
      logoText: "風 KAZE",
      logoMark: "風",
      tagline: "O vento traz o peixe fresco do dia.",
    },
    categorias: [
      { id: "pecas", nome: "Peças", emoji: "🍣" },
      { id: "quentes", nome: "Quentes", emoji: "🍜" },
      { id: "drinks", nome: "Drinks", emoji: "🍸" },
      { id: "doces", nome: "Doces", emoji: "🍵" },
    ],
    itens: [
      {
        id: "combinado-kaze",
        nome: "Combinado Kaze — 20 peças",
        descricao: "Nigiris de salmão, atum e peixe branco, uramaki e hossomaki do dia. Seleção do sushiman.",
        preco: 119,
        categoria: "pecas",
        midia: "combinado-kaze",
        pedidos30d: 860,
        pedidosMesAnterior: 790,
        curtidas: 4120,
        serve: "2 pessoas",
        tags: ["compartilhar"],
        combinaCom: "gin-yuzu",
      },
      {
        id: "ramen-tonkotsu",
        nome: "Ramen Tonkotsu",
        descricao: "Caldo de porco cozido por 14h, lámen artesanal, chashu, ovo marinado, nori e cebolinha.",
        preco: 58,
        categoria: "quentes",
        midia: "ramen-tonkotsu",
        pedidos30d: 920,
        pedidosMesAnterior: 640,
        curtidas: 3560,
        tempoPreparo: "18 min",
        destaqueDoMes: true,
        notaDoChef: "Outubro esfriou: o tonkotsu ganhou ovo extra sem custo durante o mês todo.",
        combinaCom: "soda-lichia",
      },
      {
        id: "gin-yuzu",
        nome: "Gin Tônica de Yuzu",
        descricao: "Gin japonês, tônica artesanal, yuzu e alecrim tostado.",
        preco: 39,
        categoria: "drinks",
        midia: "gin-yuzu",
        pedidos30d: 610,
        pedidosMesAnterior: 600,
        curtidas: 1480,
        tags: ["alcoolico"],
      },
      {
        id: "soda-lichia",
        nome: "Soda de Lichia",
        descricao: "Xarope de lichia da casa, água com gás e limão siciliano.",
        preco: 19,
        categoria: "drinks",
        midia: "soda-lichia",
        pedidos30d: 380,
        pedidosMesAnterior: 210,
        curtidas: 940,
        tags: ["vegetariano", "novo"],
      },
      {
        id: "petit-matcha",
        nome: "Petit Gâteau & Matcha",
        descricao: "Petit gâteau de chocolate amargo com sorvete de matcha cerimonial.",
        preco: 32,
        categoria: "doces",
        midia: "petit-matcha",
        pedidos30d: 290,
        pedidosMesAnterior: 260,
        curtidas: 1720,
        tags: ["vegetariano"],
        destaqueDoMes: true,
        notaDoChef: "A sobremesa que mais rende foto no salão.",
      },
    ],
  },
  {
    slug: "cantina-nonna",
    nome: "Cantina Nonna",
    tipo: "Cantina italiana",
    cidade: "Curitiba · PR",
    endereco: "Rua Santa Felicidade, 1890",
    horario: "Qua a Dom · 11h30 às 23h",
    instagram: "@cantinanonna.demo",
    mesas: 32,
    branding: {
      primary: "#1F6B3A",
      onPrimary: "#FFF8EC",
      accent: "#C8302B",
      bg: "#FBF4E8",
      surface: "#FFFFFF",
      text: "#2A1E14",
      muted: "#7A6A58",
      fontDisplay: "fraunces",
      fontBody: "jakarta",
      radius: 22,
      logoText: "Cantina Nonna",
      logoMark: "N",
      tagline: "Receita de família desde 1962.",
    },
    categorias: [
      { id: "pizzas", nome: "Pizzas", emoji: "🍕" },
      { id: "massas", nome: "Massas", emoji: "🍝" },
      { id: "vinhos", nome: "Vinhos & Drinks", emoji: "🍷" },
      { id: "dolci", nome: "Dolci", emoji: "🍰" },
    ],
    itens: [
      {
        id: "pizza-margherita",
        nome: "Margherita da Nonna",
        descricao: "Molho de tomate San Marzano, muçarela de búfala, manjericão fresco e azeite extravirgem.",
        preco: 74,
        categoria: "pizzas",
        midia: "pizza-margherita",
        pedidos30d: 1040,
        pedidosMesAnterior: 980,
        curtidas: 3880,
        tempoPreparo: "20 min",
        serve: "2 a 3 pessoas",
        tags: ["vegetariano", "compartilhar"],
        combinaCom: "vinho-tinto",
      },
      {
        id: "pizza-calabresa",
        nome: "Calabresa Artesanal",
        descricao: "Calabresa defumada da casa, cebola roxa, azeitonas pretas e orégano.",
        preco: 69,
        categoria: "pizzas",
        midia: "pizza-calabresa",
        pedidos30d: 1220,
        pedidosMesAnterior: 1190,
        curtidas: 2900,
        tempoPreparo: "20 min",
        serve: "2 a 3 pessoas",
        tags: ["compartilhar", "picante"],
        combinaCom: "spritz",
      },
      {
        id: "spaghetti-sugo",
        nome: "Spaghetti al Sugo",
        descricao: "Massa fresca feita na casa, sugo de tomate cozido lentamente, manjericão e parmesão.",
        preco: 58,
        categoria: "massas",
        midia: "spaghetti-sugo",
        pedidos30d: 740,
        pedidosMesAnterior: 520,
        curtidas: 2410,
        tempoPreparo: "16 min",
        tags: ["vegetariano"],
        destaqueDoMes: true,
        notaDoChef: "A receita original da Nonna Lina. Em outubro, parmesão 24 meses ralado na mesa.",
        combinaCom: "vinho-tinto",
      },
      {
        id: "vinho-tinto",
        nome: "Taça de Montepulciano",
        descricao: "Tinto italiano de corpo médio, notas de cereja e especiarias.",
        preco: 36,
        categoria: "vinhos",
        midia: "vinho-tinto",
        pedidos30d: 680,
        pedidosMesAnterior: 640,
        curtidas: 980,
        tags: ["alcoolico"],
      },
      {
        id: "spritz",
        nome: "Aperitivo Spritz",
        descricao: "Bitter de laranja, espumante, água com gás e uma rodela de laranja.",
        preco: 34,
        precoAntigo: 39,
        categoria: "vinhos",
        midia: "spritz",
        pedidos30d: 590,
        pedidosMesAnterior: 410,
        curtidas: 1650,
        tags: ["alcoolico"],
      },
      {
        id: "caipirinha",
        nome: "Caipirinha de Limão",
        descricao: "Cachaça artesanal, limão tahiti e gelo picado. A brasileira da cantina.",
        preco: 26,
        categoria: "vinhos",
        midia: "caipirinha",
        pedidos30d: 450,
        pedidosMesAnterior: 470,
        curtidas: 720,
        tags: ["alcoolico"],
      },
      {
        id: "tiramisu-nonna",
        nome: "Tiramisù",
        descricao: "Biscoito champagne no café, creme de mascarpone e cacau polvilhado na hora.",
        preco: 29,
        categoria: "dolci",
        midia: "tiramisu-nonna",
        pedidos30d: 510,
        pedidosMesAnterior: 430,
        curtidas: 2630,
        tags: ["vegetariano"],
        destaqueDoMes: true,
        notaDoChef: "Montado de manhã, servido gelado. Não chega até as 22h.",
      },
    ],
  },
]

export function getRestaurante(slug: string) {
  return RESTAURANTES.find((r) => r.slug === slug)
}
